version: '3'
services:
#  memcached:
#    image: "memcached:1.5.5"
#    ports:
#      - "11211:11211"

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
